### ISSUE TITLE
[1.8.9] crash upon skinning rabbit

### ISSUE THREAD

**Issue by kotoroshinoto** [TeamDmfMM/StarvationAhoy#26]
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) ~[ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NoSuchMethodError: dmfmm.StarvationAhoy.Meat.MeatRegistry.getModel(I)Lnet/minecraft/client/model/ModelBase;
        at dmfmm.StarvationAhoy.Meat.Block.MeatHanger.defaultABB(MeatHanger.java:153) ~[MeatHanger.class:?]
        at dmfmm.StarvationAhoy.Meat.Block.MeatHanger.func_180640_a(MeatHanger.java:137) ~[MeatHanger.class:?]
        at net.minecraft.block.Block.func_180638_a(Block.java:401) ~[afh.class:?]
        at net.minecraft.world.World.func_72945_a(World.java:1237) ~[adm.class:?]
        at net.minecraft.entity.Entity.func_70091_d(Entity.java:543) ~[pk.class:?]
        at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:98) ~[uz.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:1862) ~[adm.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699) ~[le.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1831) ~[adm.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1663) ~[adm.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544) ~[le.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701) ~[MinecraftServer.class:?]
        ... 4 more

**Comment by kotoroshinoto** [comment]
error repeats upon attempting to connect to server

**Comment by dmf444** [comment]
Thanks for reporting. Should have done more testing with this on a dedicated server. I'll try to fix it by (at the latest) tomorrow night.

**Comment by dmf444** [comment]
Fixed in StarvationAhoy-1.8.9-0.2.2.jar
