### ISSUE TITLE
some issues with Minecraft 1.12.2

### ISSUE THREAD

**Issue by Bvioto** [TeamDmfMM/StarvationAhoy#46]
Hi, I like this mod but:

**1. When I'm trying to hook off the meat hanger, it disappears. 
2. Some item textures are missing. 
3. I got a game crash, this is the log:**

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  CreativePatchingLoader (CreativeCore+v1.9.14+mc1.12.2.jar)
  EDFMLLoadingPlugin (stairdoors-1.0.jar)
  BCModPlugin (backpacks+1.12.2+-+3.4.4.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  ItemPatchingLoader (ItemPhysic+Full+1.4.10+mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 3/30/18 1:34 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at dmfmm.starvationahoy.meat.block.multiblock.CookerTileEntity.func_189518_D_(CookerTileEntity.java:33)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:176)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dmfmm.starvationahoy.meat.block.multiblock.CookerTileEntity.func_189518_D_(CookerTileEntity.java:33)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:176)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
	Level name: Allá en mi rancho chico
	All players: 1 total; [EntityPlayerMP['bvioto'/279, l='Allá en mi rancho chico', x=325.06, y=89.00, z=170.42]]
	Chunk stats: ServerChunkCache: 657 Drop: 0
	Level seed: -1996174685367939775
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"vanilla","tempScheme":"large_zones","rainScheme":"large_zones","biomeSize":"large","amplitude":1.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":false,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (232,64,100), Chunk: (at 8,4,4 in 14,6; contains blocks 224,0,96 to 239,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 801086 game time, 594689 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1206668968 bytes (1150 MB) / 5335154688 bytes (5088 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 106
	FML: MCP 9.42 Powered by Forge 14.23.2.2629 Optifine OptiFine_1.12.2_HD_U_C9 87 mods loaded, 87 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                     | Version           | Source                                        | Signature                                |
	|:--------- |:---------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft              | 1.12.2            | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                    | 9.42              | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                    | 8.0.99.99         | forge-1.12.2-14.23.2.2629.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                  | 14.23.2.2629      | forge-1.12.2-14.23.2.2629.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | creativecoredummy      | 1.0.0             | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | itemphysic             | 1.4.0             | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mercurius_updater      | 1.0               | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | uncraftingtable        | 1.8-beta6         | [1.12]UncraftingTable-1.8-beta6.jar           | None                                     |
	| UCHIJAAAA | actuallyadditions      | 1.12.2-r132       | ActuallyAdditions-1.12.2-r132.jar             | None                                     |
	| UCHIJAAAA | psi                    | r1.1-59           | Psi-r1.1-59.jar                               | None                                     |
	| UCHIJAAAA | autoreglib             | 1.3-15            | AutoRegLib-1.3-15.jar                         | None                                     |
	| UCHIJAAAA | backpacks16840         | 3.4.4             | backpacks+1.12.2+-+3.4.4.jar                  | None                                     |
	| UCHIJAAAA | bamboozled             | 1.0.10            | Bamboozled-1.12-1.0.10.jar                    | None                                     |
	| UCHIJAAAA | betterfoliage          | 2.1.10            | BetterFoliage-MC1.12-2.1.10.jar               | None                                     |
	| UCHIJAAAA | biomesoplenty          | 7.0.1.2325        | BiomesOPlenty-1.12.2-7.0.1.2325-universal.jar | None                                     |
	| UCHIJAAAA | birdsfoods             | 2.5 [1.12]        | Birds-Foods-Mod-1.12.jar                      | None                                     |
	| UCHIJAAAA | carbonado              | 1.4.2             | carbonado-1.4.2-mc1.12.x.jar                  | None                                     |
	| UCHIJAAAA | carryon                | 1.7.2             | CarryOn+MC1.12.2+v1.7.2.jar                   | None                                     |
	| UCHIJAAAA | chameleon              | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UCHIJAAAA | charcoal_pit           | 1.9               | CharcoalPit-[1.12]-1.9.jar                    | None                                     |
	| UCHIJAAAA | coffeespawner          | 1.0.2             | Coffee-Spawner-Mod-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | combustfish            | 1.0.3.2           | combustfish-1.12.2-1.0.3.2.jar                | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAAAA | cookingforblockheads   | 6.3.17            | CookingForBlockheads_1.12.1-6.3.17.jar        | None                                     |
	| UCHIJAAAA | coralreef              | 2.0               | CoralReef-2.2-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | craftelytra            | 1.2               | CraftableElytra-1.1.jar                       | None                                     |
	| UCHIJAAAA | craftingtweaks         | 8.1.8             | CraftingTweaks_1.12.2-8.1.8.jar               | None                                     |
	| UCHIJAAAA | creativecore           | 1.9.9             | CreativeCore+v1.9.14+mc1.12.2.jar             | None                                     |
	| UCHIJAAAA | defiledlands           | 1.2.0             | Defiled-Lands-Mod-1.12.2.jar                  | None                                     |
	| UCHIJAAAA | elementalcreepers      | v4.1.gf82c179     | ElementalCreepers-v4.1.gf82c179.jar           | None                                     |
	| UCHIJAAAA | endercrop              | 1.12-1.3.4        | endercrop-1.12-1.3.4.jar                      | None                                     |
	| UCHIJAAAA | gardenstuff            | 1.12-2.1.0        | GardenStuff-1.12-2.1.0.jar                    | None                                     |
	| UCHIJAAAA | giacomos_exp           | 1.2.2             | GiacomosExperienceSeedling-1.12.2-1.2.2.jar   | None                                     |
	| UCHIJAAAA | hpm                    | §aMC 1.12.2       | Harry+Potter+Mod+-+1.2.jar                    | None                                     |
	| UCHIJAAAA | harshencastle          | 0.13.1            | Harshen-Castle-Mod-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | furniture              | 2.0.3             | How'BoutThatFurniture-2.0.3.jar               | None                                     |
	| UCHIJAAAA | waila                  | 1.8.20            | Hwyla-1.8.20-B35_1.12.jar                     | None                                     |
	| UCHIJAAAA | ichunutil              | 7.1.4             | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
	| UCHIJAAAA | ic2                    | 2.8.16-ex112      | Industrialcraft-1.12.jar                      | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | ironbackpacks          | 1.12.2-3.0.5-6    | IronBackpacks-1.12.2-3.0.5-6.jar              | None                                     |
	| UCHIJAAAA | jei                    | 4.8.5.159         | jei_1.12.2-4.8.5.159.jar                      | None                                     |
	| UCHIJAAAA | journeymap             | 1.12.2-5.5.2      | JourneyMap-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | jukebox                | 1.2               | jukebox-1.2.jar                               | None                                     |
	| UCHIJAAAA | jaff                   | 1.7_for_1.12      | JustAFewFish-1.7_for_1.12.jar                 | None                                     |
	| UCHIJAAAA | justenoughbuttons      | 1.12-1.2.1        | justenoughbuttons-1.12-1.2.1.jar              | None                                     |
	| UCHIJAAAA | magipsi                | 1.3               | MagicalPsi-1.3.jar                            | None                                     |
	| UCHIJAAAA | magicclover            | 1.12-0.7.8        | magicclover-1.12-0.7.8.jar                    | None                                     |
	| UCHIJAAAA | malisiscore            | 1.12.2-6.4.0      | malisiscore-1.12.2-6.4.0.jar                  | None                                     |
	| UCHIJAAAA | malisisdoors           | 1.12.2-7.3.0      | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| UCHIJAAAA | mantle                 | 1.12-1.3.1.21     | Mantle-1.12-1.3.1.21.jar                      | None                                     |
	| UCHIJAAAA | mocreatures            | 12.0.3            | Mo-Creatures-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | tconstruct             | 1.12.2-2.9.1.65   | TConstruct-1.12.2-2.9.1.65.jar                | None                                     |
	| UCHIJAAAA | moartinkers            | 0.5.4             | moartinkers-0.5.4.jar                         | None                                     |
	| UCHIJAAAA | mobdismemberment       | 7.0.0             | MobDismemberment-1.12.2-7.0.0.jar             | None                                     |
	| UCHIJAAAA | modernlamps            | 1.0.3             | ModernLights-1.0.3_1.12.jar                   | None                                     |
	| UCHIJAAAA | openglider             | @VERSION@         | OpenGlider-1.12.1-1.1.0.jar                   | None                                     |
	| UCHIJAAAA | oreexcavation          | 1.4.113           | OreExcavation-1.4.113.jar                     | None                                     |
	| UCHIJAAAA | morepaintings          | $version          | paintings-1.12.2-3.3.0.0.jar                  | None                                     |
	| UCHIJAAAA | guilib                 | $version          | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar | None                                     |
	| UCHIJAAAA | paintingselgui         | $version          | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar | None                                     |
	| UCHIJAAAA | personalcars           | 1.4               | PersonalCars-1.4.jar                          | None                                     |
	| UCHIJAAAA | placeableitems         | 3.2               | placeableitems-3.2.jar                        | None                                     |
	| UCHIJAAAA | placebo                | 1.3.1             | Placebo-1.12.2-1.3.1.jar                      | None                                     |
	| UCHIJAAAA | plants2                | 2.6.4             | Plants-Mod-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | pcb                    | 1.5.0             | portablecraftbench-1.12.2-1.5.1.jar           | None                                     |
	| UCHIJAAAA | portalgun              | 7.0.2             | PortalGun-1.12.2-7.0.2.jar                    | None                                     |
	| UCHIJAAAA | radixcore              | 1.12.x-2.2.1      | RadixCore-1.12.x-2.2.1-universal.jar          | None                                     |
	| UCHIJAAAA | reborncore             | 3.6.11.220        | RebornCore-1.12.2-3.6.11.220-universal.jar    | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAA | rustic                 | 1.0.2             | rustic-1.0.2.jar                              | None                                     |
	| UCHIJAAAA | scannable              | 1.6.2.13          | Scannable-MC1.12-1.6.2.13.jar                 | None                                     |
	| UCHIJAAAA | soundfilters           | 0.10_for_1.12     | SoundFilters-0.10_for_1.12.jar                | None                                     |
	| UCHIJAAAA | starvationahoy         | 1.12.2-0.2.10     | starvationahoy-1.12.2-0.2.10.jar              | None                                     |
	| UCHIJAAAA | stevescarts            | 2.4.18.92         | StevesCarts-1.12.2-2.4.18.92.jar              | None                                     |
	| UCHIJAAAA | storagedrawers         | 1.12-5.2.5        | StorageDrawers-1.12.2-5.3.5.jar               | None                                     |
	| UCHIJAAAA | superminer_core        | 2.6.34.336        | SuperMiner-2.6.34.336.jar                     | None                                     |
	| UCHIJAAAA | superminer_captivator  | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar                     | None                                     |
	| UCHIJAAAA | superminer_cropinator  | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar                     | None                                     |
	| UCHIJAAAA | superminer_excavator   | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar                     | None                                     |
	| UCHIJAAAA | superminer_illuminator | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar                     | None                                     |
	| UCHIJAAAA | superminer_lumbinator  | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar                     | None                                     |
	| UCHIJAAAA | superminer_shaftanator | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar                     | None                                     |
	| UCHIJAAAA | superminer_substitutor | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar                     | None                                     |
	| UCHIJAAAA | superminer_veinator    | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar                     | None                                     |
	| UCHIJAAAA | toroquest              | 1.12.2-5.2        | toroquest-1.12.2-5.2.jar                      | None                                     |
	| UCHIJAAAA | tropicraft             | 7.1.2.57          | tropicraft-MC1.12.2-7.1.2.57.jar              | None                                     |
	| UCHIJAAAA | waddles                | 0.5.6             | Waddles-1.12.2-0.5.6.jar                      | None                                     |
	| UCHIJAAAA | wawla                  | 2.5.253           | Wawla-1.12.2-2.5.253.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | xpbook                 | 0.0.3-beta        | xpbook-1.12-0.0.3-beta.jar                    | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
CreativePatchingLoader (CreativeCore+v1.9.14+mc1.12.2.jar)
  
EDFMLLoadingPlugin (stairdoors-1.0.jar)
  com.darkenchanter.stairdoors.asm.EDClassTransformer
BCModPlugin (backpacks+1.12.2+-+3.4.4.jar)
  brad16840.core.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
ItemPatchingLoader (ItemPhysic+Full+1.4.10+mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.6.11.220
		Runtime Debofucsation 1
		RenderEngine: 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['bvioto'/279, l='Allá en mi rancho chico', x=325.06, y=89.00, z=170.42]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_C9
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL Standard v6.2.zip
	OpenGlVersion: 4.6.0 NVIDIA 388.43
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

I can't use this mod anymore on my world :c could you please help me ??

**Comment by dmf444** [comment]
Which item textures are missing?
